network: "custom"
region: "asia-northeast1"
project_id: "cloudsvcsandbox"
bucket_name: "iac_gcp_terraform_state"
instances:
  - name: "example-instance-1"
    type: "n1-standard-1"
    zone: "asia-northeast1-a"
    image: "ubuntu-2004-lts"
    disk_size_gb: 100
  - name: "example-instance-2"
    image: "ubuntu-2004-lts"
    disk_size_gb: 100
    type: "n1-standard-1"
    zone: "asia-northeast1-a"
