name: Destroy Resources by IAC tools 

env:
  STATE: "destroy"   # 可以根据需要更改初始状态, 可选create，update, destroy
  CLOUD: "gcp"       # 选择云服务商, 可选: gcp, aws, ali, azure

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/iac-pipeline-destroy.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  gcs:
    runs-on: ubuntu-latest
    needs:
      - vpc
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/gcs/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Delete Google Cloud Storage Bucket
      run: |
        gsutil -m rm -r gs://iac_gcp_terraform_state || true
        gcloud storage buckets delete gs://iac_gcp_terraform_state --quiet || true

    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -auto-approve

  vpc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/vpc/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Delete Google Cloud Router
      run: gcloud compute routers delete default-router --region=asia-northeast1 --quiet || true

    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -auto-approve
