name: Create Resources by IAC tools 

env:
  STATE: "create"    # 可以根据需要更改初始状态, 可选create，update, destroy
  CLOUD: "gcp"       # 选择云服务商, 可选: gcp, aws, ali, azure

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  gcs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/gcs/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Set up Google Cloud credentials
      run: echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > gcp-key.json

    - name: Terraform Init And Apply
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
      run: |
        terraform init
        if [ "$STATE" == "create" ]; then
            terraform apply -auto-approve
        elif [ "$STATE" == "destroy" ]; then
            terraform destroy -auto-approve
        # Add handling for other states as needed
        else
            echo "Invalid environment state"
            exit 1
        fi

    - name: Clean up Google Cloud credentials
      run: rm -f gcp-key.json 

  vpc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/vpc/
    needs:
      - gcs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Set up Google Cloud credentials
      run: echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > gcp-key.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json

    - name: Terraform Init And Apply
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
      run: |
        terraform init
        if [ "$STATE" == "create" ]; then
            terraform apply -auto-approve
        elif [ "$STATE" == "destroy" ]; then
            terraform destroy -auto-approve
        # Add handling for other states as needed
        else
            echo "Invalid environment state"
            exit 1
        fi

    - name: Clean up Google Cloud credentials
      run: rm -f gcp-key.json 
