name: Create Resources by IAC tools 

env:
  STATE: "create"    # 可以根据需要更改初始状态, 可选create，update, destroy
  CLOUD: "gcp"       # 选择云服务商, 可选: gcp, aws, ali, azure

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/iac-pipeline-create.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  gcs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/gcs/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Terraform Init And Apply
      run: bash run_terraform.sh
  network:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/network/
    needs:
      - gcs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Terraform Init And Apply
      run: bash run_terraform.sh
  vhost:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/vhost/
    needs:
      - gcs
      - network
      - key_pair

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Terraform Init And Apply
      run: bash run_terraform.sh
  key_pair:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/key_pair/
    needs:
      - gcs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Terraform Init And Apply
      run: bash run_terraform.sh
  firewall:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: IAC/modules/terraform/${{ env.CLOUD }}/firewall/
    needs:
      - gcs
      - network

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Terraform Init And Apply
      run: bash run_terraform.sh
