name: Create Resources by IAC tools 

env:
  STATE: "create"   # 可以根据需要更改初始状态, 可选create，update, destroy
  CLOUD: "gcp"       # 选择云服务商, 可选: gcp, aws, ali, azure
  TZ: Asia/Shanghai
  REPO: "artifact.onwalk.net"
  IMAGE: base/${{ github.repository }} 
  TAG: ${{ github.sha }}
  DNS_AK: ${{ secrets.DNS_AK }}
  DNS_SK: ${{ secrets.DNS_SK }}
  OSS_AK: ${{ secrets.OSS_AK }}
  OSS_SK: ${{ secrets.OSS_SK }}
  ROOT_PASSWORD: ${{ secrets.ADMIN_INIT_PASSWORD }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  GITLAB_OIDC_CLIENT_TOKEN: ${{ secrets.GITLAB_OIDC_CLIENT_TOKEN }}
  HARBOR_OIDC_CLIENT_TOKEN: ${{ secrets.HARBOR_OIDC_CLIENT_TOKEN }}
  SSH_USER: ${{ secrets.HOST_USER }}
  SSH_HOST_DOMAIN: ${{ secrets.HOST_DOMAIN }} 
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/pipeline.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  gcs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: iac_modules/terraform/${{ env.CLOUD }}/gcs/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Check if GCS bucket exists
      id: check_bucket
      run: |
        BUCKET_NAME="iac_gcp_terraform_state"
        gsutil ls -b gs://${BUCKET_NAME} || echo "::set-output name=bucket_exists::false"

    - name: Terraform Init And Apply
      if: steps.check_bucket.outputs.bucket_exists == 'false'
      run: bash run_terraform.sh
  network:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: iac_modules/terraform/${{ env.CLOUD }}/network/
    needs:
      - gcs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Terraform Init And Apply
      run: bash run_terraform.sh
  vhost:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: iac_modules/terraform/${{ env.CLOUD }}/vhost/
    needs:
      - gcs
      - network
      - key_pair

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Fetch SSH Keys
      run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > ssh_keys.pub

    - name: Terraform Init And Apply
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip jq
        python -m pip install --upgrade pip jinja2 
        python3 scripts/init.py && bash scripts/run_terraform.sh

  key_pair:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: iac_modules/terraform/${{ env.CLOUD }}/key_pair/
    needs:
      - gcs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Check if SSH Metadata exists
      id: check_ssh_metadata
      run: bash scripts/check_ssh_metadata.sh

    - name: Fetch SSH Keys
      if: steps.check_ssh_metadata.outputs.ssh_metadata_exists == 'false'
      run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > ssh_keys.pub

    - name: Terraform Init And Apply
      if: steps.check_ssh_metadata.outputs.ssh_metadata_exists == 'false'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip && python -m pip install --upgrade pip jinja2 
        python3 scripts/init.py && bash scripts/run_terraform.sh

  firewall:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: iac_modules/terraform/${{ env.CLOUD }}/firewall/
    needs:
      - gcs
      - network

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Terraform Init And Apply
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip && python -m pip install --upgrade pip jinja2
        python3 scripts/init.py && bash scripts/run_terraform.sh
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync aritfacts
        run: echo "to do"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test aritfacts
        run: echo "to do"

  setup-k3s:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - vhost
    defaults:
      run:
        shell: bash
        working-directory: playbook/ 

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set GitHub Actions output variables
        id: terraform-output
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip jq && python -m pip install --upgrade pip jinja2
          python3 scripts/init.py && terraform init
          terraform output | while read -r line; do
             if [ -z "$line" ]; then
                 break
             else
               k_v=$(echo "$line" | tr -d ' ' | awk -F= '{print $1"="$2}')
               echo "$k_v" >> $GITHUB_OUTPUT
             fi
          done
        working-directory: iac_modules/terraform/${{ env.CLOUD }}/vhost/

      - name: Pre setup && update submodule
        run: |
          sudo apt-get update && sudo apt-get install -y git
          git submodule update --init --recursive || true
          bash pre_setup.sh
        env:
          SSH_HOST_IP: ${{ steps.terraform-output.outputs.devops }}

      - name: Setup K3S Cluster
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts/inventory init_k3s_cluster_std -D
  deploy-Apps:
    runs-on: ubuntu-latest
    needs:
      - setup-k3s
    defaults:
      run:
        shell: bash
        working-directory: playbook/ 

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set GitHub Actions output variables
        id: terraform-output
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip jq && python -m pip install --upgrade pip jinja2
          python3 scripts/init.py && terraform init
          terraform output | while read -r line; do
             if [ -z "$line" ]; then
                 break
             else
               k_v=$(echo "$line" | tr -d ' ' | awk -F= '{print $1"="$2}')
               echo "$k_v" >> $GITHUB_OUTPUT
             fi
          done
        working-directory: iac_modules/terraform/${{ env.CLOUD }}/vhost/

      - name: Pre setup && update submodule
        run: |
          sudo apt-get update && sudo apt-get install -y git && git submodule update --init --recursive
          bash pre_setup.sh
        env:
          SSH_HOST_IP: ${{ steps.terraform-output.outputs.example-instance-1 }}

      - name: Deploy Gitlab
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts/inventory init_gitlab -D

      - name: Deploy Harbor
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts/inventory init_harbor -D

      - name: Deploy Chartmuseum 
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts/inventory init_chartmuseum -D
